name: Unit tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Needed for chromatic
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: install
      run: |
        yarn
    - name: test
      run: |
        yarn test
    - name: lint
      run: |
        yarn lint
    - name: chromatic
      run: |
        yarn chromatic --exit-zero-on-changes

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    # Build artifacts are only needed for releasing workflow.
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - run: yarn pack
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}
        path: |
          ${{ github.workspace }}/*.tgz

