name: Unit tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ hashFiles('**/yarn.lock') }}
    - name: install
      run: |
        yarn
    - name: test
      run: |
        yarn test
    - name: lint
      run: |
        yarn lint
    - name: chromatic
      run: |
        yarn chromatic --exit-zero-on-changes
